######################################################################
# Automatically generated by qmake (2.01a) pt. sty 9 18:54:52 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += editor.hpp
SOURCES += editor.cpp main.cpp
