######################################################################
# Automatically generated by qmake (2.01a) pt. gru 26 14:51:31 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
