######################################################################
# Automatically generated by qmake (2.01a) pon. sty 12 12:31:30 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT+= sql

# Input
SOURCES += main.cpp
