######################################################################
# Automatically generated by qmake (2.01a) sob. gru 27 15:23:44 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
