######################################################################
# Automatically generated by qmake (2.01a) pt. gru 26 17:12:03 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
