######################################################################
# Automatically generated by qmake (2.01a) pt. gru 26 15:57:50 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
