######################################################################
# Automatically generated by qmake (2.01a) niedz. sty 11 18:20:46 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += sql
# Input
SOURCES += main.cpp
